---
services: docker

env:
  # Test source install on latest supported OSes.
  - distro: centos7
    playbook: test-source.yml
    GIT_VERSION: 2.9.3
  - distro: fedora24
    playbook: test-source.yml
    GIT_VERSION: 2.9.3
  - distro: ubuntu1604
    playbook: test-source.yml
    GIT_VERSION: 2.9.3

  # Test package install on all supported OSes.
  - distro: centos7
    playbook: test.yml
    GIT_VERSION: 1.8.3.1
  - distro: centos6
    playbook: test.yml
    GIT_VERSION: 1.7.1
  - distro: fedora24
    playbook: test.yml
    GIT_VERSION: 2.7.5
  - distro: ubuntu1604
    playbook: test.yml
    GIT_VERSION: 2.7.4
  - distro: ubuntu1404
    playbook: test.yml
    GIT_VERSION: 1.9.1
  - distro: ubuntu1204
    playbook: test.yml
    GIT_VERSION: 1.7.9.5
  - distro: debian8
    playbook: test.yml
    GIT_VERSION: 2.1.4
  - distro: debian9
    playbook: test.yml
    GIT_VERSION: 2.17.0
script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure Git is installed and at the right version.
  - 'docker exec --tty ${container_id} env TERM=xterm which git'
  - 'docker exec --tty ${container_id} env TERM=xterm test -x /usr/bin/git'

  - 'docker exec --tty ${container_id} env TERM=xterm git --version'
  - 'docker exec --tty ${container_id} env TERM=xterm /usr/bin/git --version | grep -qF "$GIT_VERSION"'

notifications:
  slack:
    secure: Vqain3+LwfOBkWqAtm+7UqXpSz0S5pAnq3mgb6w4voL0KoDcsBLnr+1TfH9kWIkKBMi8ZXIa7JKMtsjKzbCNywY6TJGS5uWDU4u9KibY/3hMe2ZmSamaVa9GG3Pg0OmF41zdoOI+nfABFZO8MQ47scexgUrgCVgxsoQs2dFVpsi2wYxI5GTESGitEErg1JACin8pX608EUsAE4MOAp6VwJrb+0r1wJLy9HkyG6PPN8T7PvjVUIcBMVpbW9mdQ0gVXH+DK3M674h4q3PR0W7Yw/jkdKS1pq27nw17WNpaIBfog5+tE+/JTFF5QZeqweW7X9z3nj9n3muwbnP3sS11TBA/7bJYeJq0vcnZR/zuS3MT8lTdPnRN4JVF4niamwOl9OigBB5xOo9xEMtvwVIk5b2TMyaLeBC4GrR+V+o6FEdmuFTXlcA0U9JwC5j+ua5IEiusyJtljgB437GAlxmygq8lUZa+AI0XqKGfD1DWqHkKHfDENP85s3nUtiI0C80a49/maDdYN2zeuNflnnubAGgJA0XZyMuD8uFbQidmox4KVfUk4wizwucYFQFBIpsut38io3F+EvFW5Vc4pRau4TF0HjYH4xBEuxRHU7lgP1VzDNsYr26qqj4meAvZdMJ0/ltK8/bfFDns9uEr6Y1Us3FSwCwfFoIJ+Z+Q9tVHmuE=
