---
- name: Ensure git is installed (RedHat).
  package:
    name: "{{ git_packages }}"
    state: present
    enablerepo: "{{ git_enablerepo | default(omit, true) }}"
  when:
    - not git_install_from_source | bool
    - ansible_os_family == 'RedHat'

- name: Update apt cache (Debian).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Ensure git is installed (Debian).
  apt:
    name: "{{ git_packages }}"
    state: present
  when:
    - not git_install_from_source | bool
    - ansible_os_family == 'Debian'

# Install git from source when git_install_from_source is true.
- include: install-from-source.yml
  when: git_install_from_source | bool

  # Install the default templates
- name: Git | Push global config file
  template:
    src: git-config.j2
    dest: /etc/gitconfig
  tags: git
  become: true
